version: '3.7'

services:
  licensingservice:
    image: ostock/licensing-service:latest
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
      - "SPRING_CONFIG_IMPORT=http://localhost:8071"

    networks:
      backend:
        aliases:
          - "licenseservice"

networks:
  backend:
    driver: bridge

